pipeline:
  build:
    image: nrc/centos8-python3
    pull: true
    commands:
      - yum install -y git-core
      - yum install -y libjpeg-turbo-devel libpng-devel libcurl-devel openssl-devel
      - yum install -y python2 python2-devel python2-pip python2-virtualenv
      - make venv
      - make package

  s3:
    image: plugins/s3
    bucket: nrcbuilds
    acl: private
    region: eu-west-1
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY ]
    source: builds/${DRONE_COMMIT_SHA}.tar.gz
    target: github.com/nrcmedia/thumbor/${DRONE_COMMIT_BRANCH}
    strip_prefix: builds/
    when:
      owner: nrcmedia
      event: [push, tag, deployment]
